FROM nginx:1.27-alpine

RUN apk add --no-cache gettext   # for envsubst

COPY nginx.conf                /etc/nginx/conf.d/default.conf
COPY frontend                  /usr/share/nginx/html
COPY config.json.template      /config.json.template
COPY web-entrypoint.sh         /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
